            self.Step (Message = "Receptionist-N: Busy doing other things (allowing FreeSWITCH to time out).")
            self.Step (Message = "FreeSWITCH: pause timed out")
            self.Step (Message = "FreeSWITCH->Call-Flow-Control: queued-unavailable: <call ID>")
            self.Step (Message = "FreeSWITCH->Caller: De har ringet til <reception name>. Vent venligst.")
            self.Call_Announced_As_Locked (Call_ID = Call_ID)
            self.Step (Message = "Client-N->Receptionist-N: Queue: <reception name> (optaget)")
