            self.Step (Message = "Receptionist-N: Busy doing other things (allowing FreeSWITCH to time out).", Delay_In_Seconds = 3.0)
            self.Step (Message = "FreeSWITCH: pause timed out")
            self.Step (Message = "FreeSWITCH         ->> Call-Flow-Control: queued-unavailable: <call ID>")
            self.Step (Message = "FreeSWITCH         ->> Opkalder          »De har ringet til <reception name>. Vent venligst.«")
            self.Call_Announced_As_Locked (Call_ID = Call_ID)
            self.Step (Message = "Klient-N           ->  Receptionist-N: Queue: <reception name> (optaget)")
